spring:
  application:
    name: flashcard
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/ # 로컬 파일 시스템에서 직접 읽도록 설정 (강력한 방법)
    check-template-location: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources # 감시할 경로 명시
    livereload:
      enabled: true
  web:
    resources:
      static-locations: file:src/main/resources/static/ # 정적 파일도 실시간 반영

  datasource:
    url: jdbc:postgresql://localhost:5432/placecard?currentSchema=base
    username: postgres
    password: 1234 # 실제 비밀번호로 변경해주세요!
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update # 엔티티 구조 변경 시 DB에 반영 (배포 시에는 validate나 none 권장)
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
    show-sql: true # 실행되는 SQL 로그 출력
